# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_newsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='action',
            field=models.CharField(default='create_project', max_length=50),
            preserve_default=False,
        ),
    ]
