# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20170612_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='wiki',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
