# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170610_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='style',
            field=models.CharField(default='light', max_length=5),
        ),
    ]
